#!/bin/bash
set -euxo pipefail

# Ensure unzip and curl are available via apt.txt

# Download the kernel ZIP
curl -fLO https://github.com/dflib/jjava/releases/download/1.0-a4/jjava-1.0-a4-kernelspec.zip

# Run the Python script to install the kernel
python3 install_kernel.py
