#!/bin/bash
curl -LO https://github.com/dflib/jjava/releases/download/v1.3.0/jjava-1.3.0-kernelspec.zip
unzip jjava-1.3.0-kernelspec.zip
jupyter kernelspec install jjava-1.3.0-kernelspec --user --name=java
