#!/bin/bash
curl -LO https://github.com/dflib/jjava/releases/download/1.0-a4/jjava-1.0-a4-kernelspec.zip 
unzip jjava-1.3.0-kernelspec.zip
jupyter kernelspec install jjava-1.3.0-kernelspec --user --name=java
